POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 1,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/cfb8eaf6-5100-4c59-be59-9ed06c9abc5c/attendees
Content-Type: application/json

{
  "name": "Ronaldo Reis",
  "email": "ronaldo@rocketseat.com.br"
}

###

GET http://localhost:3333/events/cfb8eaf6-5100-4c59-be59-9ed06c9abc5c

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/cfb8eaf6-5100-4c59-be59-9ed06c9abc5c/attendees?query=ronaldo